import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import '../../styles/_reset.scss';
import {Providers} from '@/../../redux/provider';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Sage & rosemary',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // If you are using Pages router, do these changes to your _app.ts file.
        <Providers>
            <html lang="en">
            <body className={inter.className}>{children}</body>
            </html>
        </Providers>
    );
}
